// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kCZg0ZXC1-tpph7VBp0fHNk7k1gaqvU',
    appId: '1:1006803559445:web:99d24ee2091da20645da1c',
    messagingSenderId: '1006803559445',
    projectId: 'todoriverpod-fea5d',
    authDomain: 'todoriverpod-fea5d.firebaseapp.com',
    storageBucket: 'todoriverpod-fea5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5X6I9rVYy_xZQ_56-mDl_woADSNCpMU',
    appId: '1:1006803559445:android:ad5fff1fd15c709d45da1c',
    messagingSenderId: '1006803559445',
    projectId: 'todoriverpod-fea5d',
    storageBucket: 'todoriverpod-fea5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2b_18_HFpR2Y9c4soPjEDFIbKN42243o',
    appId: '1:1006803559445:ios:13572c46f265e0b745da1c',
    messagingSenderId: '1006803559445',
    projectId: 'todoriverpod-fea5d',
    storageBucket: 'todoriverpod-fea5d.appspot.com',
    iosClientId: '1006803559445-ad031ms05fi8b5ics5522fc66h45tibh.apps.googleusercontent.com',
    iosBundleId: 'com.ankurewu.toDoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2b_18_HFpR2Y9c4soPjEDFIbKN42243o',
    appId: '1:1006803559445:ios:0b5308fb6ff2b26745da1c',
    messagingSenderId: '1006803559445',
    projectId: 'todoriverpod-fea5d',
    storageBucket: 'todoriverpod-fea5d.appspot.com',
    iosClientId: '1006803559445-nq0ifr9oac28lktd0f2dnrp3l16b64lt.apps.googleusercontent.com',
    iosBundleId: 'com.ankurewu.toDoRiverpod.RunnerTests',
  );
}
